services:
    wix_base.decoder:
        class: Wix\BaseBundle\Instance\Decoder
        arguments: [%wix_base.config.keys%]

    wix_base.controller.listener:
        class: Wix\BaseBundle\EventListener\ControllerListener
        arguments: [@annotation_reader, @wix_base.decoder]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    wix_base.debug_toolbar:
        class: Wix\BaseBundle\DataCollector\DebugToolbar
        arguments: [@wix_base.decoder, %wix_base.config.keys%]
        tags:
            - { name: data_collector, template: "WixBaseBundle:Collector:toolbar.html.twig", id: "wix_base_debug_toolbar" }